version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./reservation-system.sql:/docker-entrypoint-initdb.d/reservation-system.sql
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
