version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
